### ISSUE TITLE
livenessProbe shuts down tunnel to early

### ISSUE THREAD

**Issue by henrikperssonvermiculus** [cloudflare/argo-tunnel-examples#18]
Hi, using the manifest with the following settings 

        livenessProbe:
          httpGet:
            # Cloudflared has a /ready endpoint which returns 200 if and only if
            # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10

My tunnel shuts down to early, most likely because this:
Liveness probe failed: Get "[http://10.244.4.35:2000/ready":](http://10.244.4.35:2000/ready%22:) dial tcp 10.244.4.35:2000: connect: connection

When I removed livenessProbe tunnel seems to be okay.
Are there any updated livenessProbe settings to use?

I am using tunnel version 2022.2.1

**Comment by nmldiegues** [comment]
Liveness probes are recommended so that, should any drastic problem happen and the tunnel has no connections alive, the pod is restarted.

We have similar configuration in some of our production tunnels. The difference is that we are not so aggressive with the probe. We have a higher failure threshold and a higher initial delay (1min)

**Comment by henrikperssonvermiculus** [comment]
Are you able to share your configuration?

I really want to use Liveness probes but tried some changes in the configuration but I did not work out well.

**Comment by nmldiegues** [comment]
Sure. E.g.:
```
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 30
          periodSeconds: 30
```
