### ISSUE TITLE
How can I use helm-chart repository to install the chart?

### ISSUE THREAD

**Issue by holms** [cloudflare/argo-tunnel-examples#26]
Well [this](https://github.com/cloudflare/argo-tunnel-examples/tree/master/helm/cloudflare-tunnel) is the chart for helm which is not possible to access at all. Wheres the helm-chart repository? 

You have official cloudflare helm-chart repo in here: https://github.com/cloudflare/helm-charts but the only chart is this one https://github.com/cloudflare/helm-charts/tree/master/charts/argo-tunnel and it's a legacy argo ingress controller which doesn't work anymore. Why not to put this chart in there and destroy that legacy one? I'm actually need this heavily for automation, I don't want to fork your repo or store chart locally. Can I contribute somehow in here please? We "SIA Setupad" your enterprise client.

**Comment by holms** [comment]
@nmldiegues  can we do something about it together with @mattalberts? Because it's currently absolutely unusable for anyone, and I think cloudflare should be ready to fully support deployment to kubernetes :) I can push the PR but I don't know what to do with legacy version, should be just replace it? Should this new chart stay in this repo or move to `cloudflare/helm-charts`

**Comment by abelinkinbio** [comment]
@holms apologies for the confusion, but I believe you are looking for this [guide](https://github.com/cloudflare/argo-tunnel-examples/tree/master/helm/cloudflare-tunnel). If you're able to confirm that this example lines up better to your expectations we can ensure we deprecate the legacy documentation as well.

**Comment by TomKeur** [comment]
@abelinkinbio 
I would also to see this as a public Helm Chart, for now I found a 3rd party Helm Chart, https://artifacthub.io/packages/helm/rlex/cloudflare-tunnel

But I guess it will be better if Cloudflare will maintain it, because of security concerns.

Also I would like change the Deployment type from: `kind: Deployment` to `kind: DaemonSet` because I want to run more than one Tunnel pod for high availability, but I can guess we can use `values.yaml` for this (we need to make it configurable).

Why I want a public Helm Chart? We're using Argo CD to deploy our K8s infra (Ingress, etc.), so would love to be able to manage Cloudflare tunnel this way. We cannot simply add a GitHub URL, because when something changes, our deployment maybe breaks.
Maintaining the Helm Chart in our Infra repo is possible, but then we'll need to maintain it when new versions of `cloudflared` are released.

**Comment by asychev** [comment]
Any updates on this?

**Comment by dstewen** [comment]
I would also like to request an update to the helm chart for running cloudflared.

With the changes to the way tunnel gets deployed in the site https://one.dash.cloudflare.com/ it is possible to deploy via docker using the web site that does a form of dynamic changing of the ingress rules. For example you add a new app in the web interface and within seconds it updates in the docker container.

This removes the need for the static config.yaml file.

**Comment by holms** [comment]
@abelinkinbio  I've discussed this situation with our account managers in Cloudflare and they also think best solution is to move this chart to here: https://github.com/cloudflare/helm-charts Otherwise there's no way to install this chart directly from helm. I actually have no idea would this PR be accepted, because I need to remove old chart from cloudflare/helm-charts repo first.

**Comment by obezuk** [comment]
Argo Tunnels has been sunset and it is reasonable for us to replace the legacy helm chart with one for Cloudflare Tunnels.

There is already a PR available for this here: https://github.com/cloudflare/helm-charts/pull/25 Let's continue this discussion over there.
